mv 1_xml.zip 憲法 .zip; mkdir 憲法; cd 憲法; unzip 憲法.zip ; cd ..
mv 2_xml.zip 刑事 .zip; mkdir 刑事; cd 刑事; unzip 刑事.zip ; cd ..
mv 3_xml.zip 財務通則 .zip; mkdir 財務通則; cd 財務通則; unzip 財務通則.zip ; cd ..
mv 4_xml.zip 水産業 .zip; mkdir 水産業; cd 水産業; unzip 水産業.zip ; cd ..
mv 5_xml.zip 観光 .zip; mkdir 観光; cd 観光; unzip 観光.zip ; cd ..
mv 6_xml.zip 国会 .zip; mkdir 国会; cd 国会; unzip 国会.zip ; cd ..
mv 7_xml.zip 警察 .zip; mkdir 警察; cd 警察; unzip 警察.zip ; cd ..
mv 8_xml.zip 国有財産 .zip; mkdir 国有財産; cd 国有財産; unzip 国有財産.zip ; cd ..
mv 9_xml.zip 鉱業 .zip; mkdir 鉱業; cd 鉱業; unzip 鉱業.zip ; cd ..
mv 10_xml.zip 郵務 .zip; mkdir 郵務; cd 郵務; unzip 郵務.zip ; cd ..
mv 11_xml.zip 行政組織 .zip; mkdir 行政組織; cd 行政組織; unzip 行政組織.zip ; cd ..
mv 12_xml.zip 消防 .zip; mkdir 消防; cd 消防; unzip 消防.zip ; cd ..
mv 13_xml.zip 国税 .zip; mkdir 国税; cd 国税; unzip 国税.zip ; cd ..
mv 14_xml.zip 工業 .zip; mkdir 工業; cd 工業; unzip 工業.zip ; cd ..
mv 15_xml.zip 電気通信 .zip; mkdir 電気通信; cd 電気通信; unzip 電気通信.zip ; cd ..
mv 16_xml.zip 国家公務員 .zip; mkdir 国家公務員; cd 国家公務員; unzip 国家公務員.zip ; cd ..
mv 17_xml.zip 国土開発 .zip; mkdir 国土開発; cd 国土開発; unzip 国土開発.zip ; cd ..
mv 18_xml.zip 事業 .zip; mkdir 事業; cd 事業; unzip 事業.zip ; cd ..
mv 19_xml.zip 商業 .zip; mkdir 商業; cd 商業; unzip 商業.zip ; cd ..
mv 20_xml.zip 労働 .zip; mkdir 労働; cd 労働; unzip 労働.zip ; cd ..
mv 21_xml.zip 行政手続 .zip; mkdir 行政手続; cd 行政手続; unzip 行政手続.zip ; cd ..
mv 22_xml.zip 土地 .zip; mkdir 土地; cd 土地; unzip 土地.zip ; cd ..
mv 23_xml.zip 国債 .zip; mkdir 国債; cd 国債; unzip 国債.zip ; cd ..
mv 24_xml.zip 金融・保険 .zip; mkdir 金融・保険; cd 金融・保険; unzip 金融・保険.zip ; cd ..
mv 25_xml.zip 環境保全 .zip; mkdir 環境保全; cd 環境保全; unzip 環境保全.zip ; cd ..
mv 26_xml.zip 統計 .zip; mkdir 統計; cd 統計; unzip 統計.zip ; cd ..
mv 27_xml.zip 都市計画 .zip; mkdir 都市計画; cd 都市計画; unzip 都市計画.zip ; cd ..
mv 28_xml.zip 教育 .zip; mkdir 教育; cd 教育; unzip 教育.zip ; cd ..
mv 29_xml.zip 外国為替・貿易 .zip; mkdir 外国為替・貿易; cd 外国為替・貿易; unzip 外国為替・貿易.zip ; cd ..
mv 30_xml.zip 厚生 .zip; mkdir 厚生; cd 厚生; unzip 厚生.zip ; cd ..
mv 31_xml.zip 地方自治 .zip; mkdir 地方自治; cd 地方自治; unzip 地方自治.zip ; cd ..
mv 32_xml.zip 道路 .zip; mkdir 道路; cd 道路; unzip 道路.zip ; cd ..
mv 33_xml.zip 文化 .zip; mkdir 文化; cd 文化; unzip 文化.zip ; cd ..
mv 34_xml.zip 陸運 .zip; mkdir 陸運; cd 陸運; unzip 陸運.zip ; cd ..
mv 35_xml.zip 社会福祉 .zip; mkdir 社会福祉; cd 社会福祉; unzip 社会福祉.zip ; cd ..
mv 36_xml.zip 地方財政 .zip; mkdir 地方財政; cd 地方財政; unzip 地方財政.zip ; cd ..
mv 37_xml.zip 河川 .zip; mkdir 河川; cd 河川; unzip 河川.zip ; cd ..
mv 38_xml.zip 産業通則 .zip; mkdir 産業通則; cd 産業通則; unzip 産業通則.zip ; cd ..
mv 39_xml.zip 海運 .zip; mkdir 海運; cd 海運; unzip 海運.zip ; cd ..
mv 40_xml.zip 社会保険 .zip; mkdir 社会保険; cd 社会保険; unzip 社会保険.zip ; cd ..
mv 41_xml.zip 司法 .zip; mkdir 司法; cd 司法; unzip 司法.zip ; cd ..
mv 42_xml.zip 災害対策 .zip; mkdir 災害対策; cd 災害対策; unzip 災害対策.zip ; cd ..
mv 43_xml.zip 農業 .zip; mkdir 農業; cd 農業; unzip 農業.zip ; cd ..
mv 44_xml.zip 航空 .zip; mkdir 航空; cd 航空; unzip 航空.zip ; cd ..
mv 45_xml.zip 防衛 .zip; mkdir 防衛; cd 防衛; unzip 防衛.zip ; cd ..
mv 46_xml.zip 民事 .zip; mkdir 民事; cd 民事; unzip 民事.zip ; cd ..
mv 47_xml.zip 建築・住宅 .zip; mkdir 建築・住宅; cd 建築・住宅; unzip 建築・住宅.zip ; cd ..
mv 48_xml.zip 林業 .zip; mkdir 林業; cd 林業; unzip 林業.zip ; cd ..
mv 49_xml.zip 貨物運送 .zip; mkdir 貨物運送; cd 貨物運送; unzip 貨物運送.zip ; cd ..
mv 50_xml.zip 外事 .zip; mkdir 外事; cd 外事; unzip 外事.zip ; cd ..
