grep "^01" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-01.csv
grep "^02" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-02.csv
grep "^03" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-03.csv
grep "^04" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-04.csv
grep "^05" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-05.csv
grep "^06" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-06.csv
grep "^07" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-07.csv
grep "^08" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-08.csv
grep "^09" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-09.csv
grep "^10" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-10.csv
grep "^11" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-11.csv
grep "^12" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-12.csv
grep "^13" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-13.csv
grep "^14" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-14.csv
grep "^15" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-15.csv
grep "^16" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-16.csv
grep "^17" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-17.csv
grep "^18" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-18.csv
grep "^19" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-19.csv
grep "^20" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-20.csv
grep "^21" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-21.csv
grep "^22" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-22.csv
grep "^23" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-23.csv
grep "^24" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-24.csv
grep "^25" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-25.csv
grep "^26" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-26.csv
grep "^27" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-27.csv
grep "^28" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-28.csv
grep "^29" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-29.csv
grep "^30" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-30.csv
grep "^31" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-31.csv
grep "^32" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-32.csv
grep "^33" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-33.csv
grep "^34" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-34.csv
grep "^35" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-35.csv
grep "^36" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-36.csv
grep "^37" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-37.csv
grep "^38" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-38.csv
grep "^39" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-39.csv
grep "^40" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-40.csv
grep "^41" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-41.csv
grep "^42" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-42.csv
grep "^43" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-43.csv
grep "^44" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-44.csv
grep "^45" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-45.csv
grep "^46" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-46.csv
grep "^47" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-47.csv
grep "^48" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-48.csv
grep "^49" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-49.csv
grep "^50" bunruiwall-sort-uniq2.csv > bunruiwall-sort-uniq-50.csv
